steps:
  # Build & push l'image Docker du serveur
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'europe-west1-docker.pkg.dev/adminserein/cloud-run-source-deploy/server:latest'
      - '-f'
      - 'apps/server/Dockerfile'
      - '.'

images:
  - 'europe-west1-docker.pkg.dev/adminserein/cloud-run-source-deploy/server:latest'

  # Déploiement sur Cloud Run (service backend)
  # Assure-toi d'avoir activé l'API Cloud Run et que le compte de build a le rôle Cloud Run Admin.
  # Adapte le nom de service "server" si tu en utilises un autre.
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'server'
      - '--image=europe-west1-docker.pkg.dev/adminserein/cloud-run-source-deploy/server:latest'
      - '--region=europe-west1'
      - '--platform=managed'
      - '--allow-unauthenticated'
