steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'europe-west1-docker.pkg.dev/adminserein/cloud-run-source-deploy/web:latest'
      - '-f'
      - 'apps/web/Dockerfile'
      - '.'
images:
  - 'europe-west1-docker.pkg.dev/adminserein/cloud-run-source-deploy/web:latest'
